
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 05 23:28:52 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 7;
  public static final int GRT = 27;
  public static final int GRTEQ = 28;
  public static final int LPAREN = 17;
  public static final int CONTINUE = 11;
  public static final int LESS = 29;
  public static final int FOR = 10;
  public static final int MINUS = 12;
  public static final int RPAREN = 18;
  public static final int SEMICOLON = 5;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int COMMA = 22;
  public static final int INC = 33;
  public static final int DIV = 13;
  public static final int PLUS = 21;
  public static final int ASSIGN = 35;
  public static final int LESSEQ = 30;
  public static final int IF = 25;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int NUMBER = 38;
  public static final int MOD = 15;
  public static final int IDENT = 39;
  public static final int BREAK = 6;
  public static final int VOID = 24;
  public static final int EQ = 19;
  public static final int LBRACK = 36;
  public static final int LBRACE = 3;
  public static final int ELSE = 26;
  public static final int RBRACK = 37;
  public static final int READ = 9;
  public static final int CHARCONST = 40;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 41;
  public static final int PROG = 2;
  public static final int DEC = 34;
  public static final int PRINT = 23;
  public static final int NOTEQ = 16;
}

