package rs.ac.bg.etf.pp1;

public class sym_old {
	 public static final int CONST = 8;
	  public static final int GRT = 29;
	  public static final int GRTEQ = 30;
	  public static final int LPAREN = 18;
	  public static final int CONTINUE = 12;
	  public static final int LESS = 31;
	  public static final int FOR = 11;
	  public static final int MINUS = 13;
	  public static final int RPAREN = 19;
	  public static final int SEMICOLON = 5;
	  public static final int AND = 33;
	  public static final int OR = 34;
	  public static final int COMMA = 23;
	  public static final int INC = 35;
	  public static final int DIV = 14;
	  public static final int PLUS = 22;
	  public static final int ASSIGN = 37;
	  public static final int LESSEQ = 32;
	  public static final int IF = 27;
	  public static final int DOT = 38;
	  public static final int EOF = 0;
	  public static final int RETURN = 21;
	  public static final int NEW = 9;
	  public static final int error = 1;
	  public static final int MUL = 15;
	  public static final int NUMBER = 26;
	  public static final int MOD = 16;
	  public static final int IDENT = 43;
	  public static final int BREAK = 6;
	  public static final int VOID = 25;
	  public static final int EQ = 20;
	  public static final int LBRACK = 39;
	  public static final int LBRACE = 3;
	  public static final int ELSE = 28;
	  public static final int RBRACK = 40;
	  public static final int ENUM = 7;
	  public static final int READ = 10;
	  public static final int CHARCONST = 41;
	  public static final int RBRACE = 4;
	  public static final int BOOLCONST = 42;
	  public static final int PROG = 2;
	  public static final int DEC = 36;
	  public static final int PRINT = 24;
	  public static final int NOTEQ = 17;		
}
